global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
  - job_name: "prometheus"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "express_api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "golang_api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5001"]

  - job_name: "no_deps_js"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5003"]
